import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScroll from "@/components/SmoothScroll";
import { Roboto } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto( {weight: '300', subsets: ['latin']})


export const metadata: Metadata = {
  title: "NoteWrite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SmoothScroll>
          <Providers>
            <Navbar/>            
               {children}          
            <Footer />
          </Providers>
        </SmoothScroll>
      </body>
    </html>
  );
}
